update_data:
  name: Update Portfolio Data
  description: Manually trigger portfolio data update from all configured sources.
  fields: {}

run_analytics:
  name: Run Portfolio Analytics
  description: Run portfolio analytics for the specified number of days.
  fields:
    days:
      name: Days
      description: Number of days to analyze (default: 30)
      required: false
      default: 30
      selector:
        number:
          min: 1
          max: 365
          mode: box

get_status:
  name: Get Portfolio Status
  description: Get current portfolio system status and health information.
  fields: {}